[package]
name = "number_theory_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rayon = "1.10.0"

# [dev-dependencies]
# criterion = "0.5.1"


# [[bench]]
# name = "max"
# harness = false
